import { o } from "maath/dist/index-0332b2ed.esm";
import {
    mobile,
    backend,
    creator,
    web,
    javascript,
    html,
    css,
    git,
    figma,
    oerwf,
    tesla,
    shopify,
    carrent,
    jobit,
    tripguide,
    python,
    c,
    swift,
    java,
    latex,
    sql,
    postgres,
    xampp,
    php,
    abat,
    udlap,
    apple,
  } from "../assets";
  
  export const navLinks = [
    {
      id: "about",
      title: "About",
    },
    {
      id: "work",
      title: "Work",
    },
    {
      id: "contact",
      title: "Contact",
    },
  ];
  
  const services = [
    {
      title: "App Developer",
      icon: web,
    },
    {
      title: "AI/ML Developer",
      icon: mobile,
    },
    {
      title: "Novice Researcher",
      icon: backend,
    },
    {
      title: "QC Enthusiast",
      icon: creator,
    },
  ];
  
  const technologies = [
    {
      name: "Python",
      icon: python,
    },
    {
      name: "Swift",
      icon: swift,
    },
    {
      name: "C",
      icon: c,
    },
    {
      name: "Java",
      icon: java,
    },
    {
      name: "PHP",
      icon: php,
    },
    {
      name: "Postgres",
      icon: postgres,
    },
    {
      name: "Xampp",
      icon: xampp,
    },
    {
      name: "HTML 5",
      icon: html,
    },
    {
      name: "CSS 3",
      icon: css,
    },
    {
      name: "JavaScript",
      icon: javascript,
    },
    {
      name: "git",
      icon: git,
    },
    {
      name: "figma",
      icon: figma,
    },
    {
      name: "LaTeX",
      icon: latex,
    },
    
  ];
  
  const experiences = [
    {
      title: "Apple Ecosystem Development - Student",
      company_name: "Apple Developer Academy @ UNINA ",
      icon: apple,
      iconBg: "#000",
      date: "September 2024 - June 2025",
      points: [
        "Designing, crafting and developing applications for Apple ecosystem.",
        "Challenge Based Learning (CBL) academy that teaches Coding, Graphical User Interface Design (GUI), and Business",
        "Collaborating with cross-functional teams from different backgrounds and cultures.",
      ],
    },
    {
      title: "AI Intern",
      company_name: "Abat Northamerica",
      icon: abat,
      iconBg: "#fff",
      date: "January 2024 - August 2024",
      points: [
        "Enhanced an attendance registry with a facial and emotion recognition through the use of OpenCV, Keras, and TensorFlow.",
        "Achieved a reduction in internal operational costs by 30% through machine learning models on Jetson Nano and Raspberry Pi 4.",
        "Trained AI models for object recognition to detect damages and count pallets with YOLOv5, YOLOv8 and MMDetection.",
        "Designed and connected the front-end of an AI system using sockets and Streamlit.",
      ],
    },
    {
      title: "Computer Systems Engineering - Student",
      company_name: "Universidad de las Américas Puebla",
      icon: udlap,
      iconBg: "#E6DEDD",
      date: "August 2022 - December 2026 (expected)",
      points: [
        "GPA: 10.0/10.0",
        "Honors Program: Selected as part of the top 15% of the student body for academic excellence. Conducting research on artificial intelligence algorithms for realism assessment for image generated by AI under the supervision of a Ph.D professor.",
        "https://doi.org/10.1007/978-3-031-75540-8_15",
        "Programming Coursework: Algorithms and Programming, Object-Oriented Programming, Data Structures, Computational Architectures, Operating Systems, Databases.",
        "Math Coursework: Linear Algebra, Calculus I, Calculus II, Ordinary Diﬀerential Equations, Discrete Mathematics.",
      ],
    },
  ];
  
  const testimonials = [
    {
      testimonial:
        "I thought it was impossible to make a website as beautiful as our product, but Rick proved me wrong.",
      name: "Sara Lee",
      designation: "CFO",
      company: "Acme Co",
      image: "https://randomuser.me/api/portraits/women/4.jpg",
    },
    {
      testimonial:
        "I've never met a web developer who truly cares about their clients' success like Rick does.",
      name: "Chris Brown",
      designation: "COO",
      company: "DEF Corp",
      image: "https://randomuser.me/api/portraits/men/5.jpg",
    },
    {
      testimonial:
        "After Rick optimized our website, our traffic increased by 50%. We can't thank them enough!",
      name: "Lisa Wang",
      designation: "CTO",
      company: "456 Enterprises",
      image: "https://randomuser.me/api/portraits/women/6.jpg",
    },
  ];
  
  const projects = [
    {
      name: "OERWF",
      description:
        "An open educational resource for high school students for learning quantum mechanics using GeoGebra and eXeLearning.",
      tags: [
        {
          name: "eXeLearning",
          color: "blue-text-gradient",
        },
        {
          name: "html",
          color: "green-text-gradient",
        },
        {
          name: "css",
          color: "pink-text-gradient",
        },
      ],
      image: oerwf,
      source_code_link: "https://azuanymila.me/reafo/home.html",
    },
  ];
  
  export { services, technologies, experiences, testimonials, projects };