import { o } from "maath/dist/index-0332b2ed.esm";
import {
  mobile,
  backend,
  creator,
  web,
  javascript,
  html,
  css,
  git,
  figma,
  oerwf,
  python,
  c,
  swift,
  java,
  latex,
  postgres,
  xampp,
  php,
  abat,
  udlap,
  apple,
  academy,
  micai,
  stomadida,
  colorscore,
  maia,
  jorge,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "work",
    title: "Experience",
  },
  {
    id: "project",
    title: "Projects",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

const services = [
  {
    title: "App Developer",
    icon: web,
  },
  {
    title: "AI/ML Developer",
    icon: mobile,
  },
  {
    title: "Novice Researcher",
    icon: backend,
  },
  {
    title: "QC Enthusiast",
    icon: creator,
  },
];

const technologies = [
  {
    name: "Python",
    icon: python,
  },
  {
    name: "Swift",
    icon: swift,
  },
  {
    name: "C",
    icon: c,
  },
  {
    name: "Java",
    icon: java,
  },
  {
    name: "PHP",
    icon: php,
  },
  {
    name: "Postgres",
    icon: postgres,
  },
  {
    name: "Xampp",
    icon: xampp,
  },
  {
    name: "HTML 5",
    icon: html,
  },
  {
    name: "CSS 3",
    icon: css,
  },
  {
    name: "JavaScript",
    icon: javascript,
  },
  {
    name: "git",
    icon: git,
  },
  {
    name: "figma",
    icon: figma,
  },
  {
    name: "LaTeX",
    icon: latex,
  },

];

const experiences = [
  {
    title: "Software Engineer Intern",
    company_name: "Apple",
    icon: apple,
    iconBg: "#000",
    date: "May 2026 - August 2026",
    points: [
      "Architected an end-to-end VoiceOver media feature on the Media Platforms Accessibility team, integrated platform-wide.",
      "Engineered a Swift-based multimodal LLM pipeline with structured prompting and safety guardrails.",
      "Reduced pipeline latency by 30% by building a custom parameter-optimization benchmarking harness.",
      "Defined the non-visual interaction model and authored comprehensive handoff specifications for the feature.",
      "Drove refinements to audio pacing and controls through cross-functional reviews with Accessibility, QA, and Design.",
    ],
  },
  {
    title: "Instructor & Community Outreach Program Manager",
    company_name: "Jr. Developers Academy",
    icon: academy,
    iconBg: "#000",
    date: "August 2025 - Present",
    points: [
      "Designed and taught a programming curriculum for 200+ elementary students in an under-resourced community.",
      "Mentored students in Swift, breaking down complex programming topics to guide them in building their first app.",
    ],
  },
  {
    title: "Software Engineer Intern - Xcode Previews",
    company_name: "Apple",
    icon: apple,
    iconBg: "#000",
    date: "June 2025 - August 2025",
    points: [
      "Built internal SwiftUI developer tools on the Xcode Previews team to extend the functionality of Previews.",
      "Resolved issues in the display of user code error messages, ensuring UI consistency during development.",
      "Integrated LLMs to extract and present contextual insights, reducing cognitive load and boosting developer efficiency.",
    ],
  },
  {
    title: "Apple Ecosystem Development - Student",
    company_name: "Apple Developer Academy @ UNINA ",
    icon: academy,
    iconBg: "#000",
    date: "September 2024 - June 2025",
    points: [
      "Designing, crafting and developing applications for Apple ecosystem.",
      "Challenge Based Learning (CBL) academy that teaches Coding, Graphical User Interface Design (GUI), and Business",
      "Collaborating with cross-functional teams from different backgrounds and cultures.",
    ],
  },
  {
    title: "Artificial Intelligence Intern",
    company_name: "Abat Northamerica",
    icon: abat,
    iconBg: "#fff",
    date: "January 2024 - August 2024",
    points: [
      "Cut internal operational costs by 30% by developing and deploying ML models on Jetson Nano and Raspberry Pi.",
      "Trained object recognition models (YOLOv5, YOLOv8, MMDetection) to automate pallet counting and damage detection.",
      "Implemented an OpenCV/TensorFlow facial recognition system to automate attendance tracking.",
    ],
  },
  {
    title: "Computer Systems Engineering - Student",
    company_name: "Universidad de las Américas Puebla",
    icon: udlap,
    iconBg: "#E6DEDD",
    date: "August 2022 - December 2026 (expected)",
    points: [
      "GPA: 10.0/10.0",
      "Honors Program: Selected as part of the top 15% of the student body for academic excellence. Conducting research on artificial intelligence algorithms for realism assessment for image generated by AI under the supervision of a Ph.D professor.",
      "https://doi.org/10.1007/978-3-031-75540-8_15",
      "Programming Coursework: Algorithms and Programming, Object-Oriented Programming, Data Structures, Computational Architectures, Operating Systems, Databases.",
      "Math Coursework: Linear Algebra, Calculus I, Calculus II, Ordinary Diﬀerential Equations, Discrete Mathematics.",
    ],
  },
];

const testimonials = [
  {
    testimonial: "During my time working with Azuany, I have discovered that despite her young age, she is a talented, hardworking, committed and highly capable computer systems engineering student who excels in artificial intelligence and python development. She has remarkably completed her tasks surpassing the performance of other interns and junior developers.",
    name: "Jorge García",
    designation: "AI Developer",
    company: "abat Northamerica",
    image: jorge
  },
];

const projects = [
  {
    name: "MAIA: Mobility AI Analytics",
    description:
      "Mobility & AI Hackathon 2025 (1st Place). An AI-powered platform transforming city transport by turning social feedback into actionable insights for authorities.",
    tags: [
      {
        name: "React",
        color: "blue-text-gradient",
      },
      {
        name: "JavaScript",
        color: "green-text-gradient",
      },
      {
        name: "AI",
        color: "pink-text-gradient",
      },
    ],
    image: maia,
    source_code_link: "https://github.com/JorgeVenegas/zepedapp.git",
    className: "md:col-span-2 md:row-span-2",
  },
  {
    name: "ColorScore",
    description:
      "Real-time iOS app for color-blind soccer fans. Utilizes Core ML and computer vision to distinguish players on the field.",
    tags: [
      {
        name: "Swift",
        color: "blue-text-gradient",
      },
      {
        name: "iOS",
        color: "green-text-gradient",
      },
      {
        name: "ML",
        color: "pink-text-gradient",
      },
    ],
    image: colorscore,
    source_code_link: "https://github.com/azu-any/AppAccesibilidad.git",
    className: "md:col-span-1 md:row-span-2",
  },
  {
    name: "Stomadida",
    description:
      "Interactive 3D ostomy care tutorials on iPadOS & visionOS. Validated by international healthcare professionals (FAIS). Features multilingual support and geolocation.",
    tags: [
      {
        name: "Swift",
        color: "blue-text-gradient",
      },
      {
        name: "iPadOS",
        color: "green-text-gradient",
      },
      {
        name: "visionOS",
        color: "pink-text-gradient",
      },
    ],
    image: stomadida,
    source_code_link: "https://apps.apple.com/us/app/stomadida-stoma-care-guide/id6746772397",
    className: "md:col-span-1 md:row-span-1",
  },
  {
    name: "QCourse 551-1",
    description:
      "Interactive quantum computing course with Classiq, featuring Jupyter notebooks and hands-on exercises for Grover's algorithm.",
    tags: [
      {
        name: "Quantum",
        color: "blue-text-gradient",
      },
      {
        name: "EduTech",
        color: "green-text-gradient",
      },
      {
        name: "Jupyter",
        color: "pink-text-gradient",
      },
    ],
    image: creator,
    source_code_link: "https://gitlab.com/alvarorgomez/introduction-to-quantum-computing-with-classiq/-/tree/72d0429a227c5666f5fa95bd04373479c0edf121/",
    className: "md:col-span-1 md:row-span-1",
  },
  {
    name: "AI Image Coherence",
    description:
      "Published Springer paper surveying metrics for assessing realism in AI-generated images.",
    tags: [
      {
        name: "AI",
        color: "blue-text-gradient",
      },
      {
        name: "Research",
        color: "green-text-gradient",
      },
      {
        name: "Python",
        color: "pink-text-gradient",
      },
    ],
    image: micai,
    source_code_link: "https://link.springer.com/chapter/10.1007/978-3-031-75540-8_15",
    className: "md:col-span-2 md:row-span-1",
  },
  {
    name: "OERWF",
    description:
      "Open educational resource for high school physics, modeling wave functions with GeoGebra.",
    tags: [
      {
        name: "EduTech",
        color: "blue-text-gradient",
      },
      {
        name: "HTML/CSS",
        color: "green-text-gradient",
      },
    ],
    image: oerwf,
    source_code_link: "https://azuanymila.me/reafo/home.html",
    className: "md:col-span-1 md:row-span-1",
  },
];

export { services, technologies, experiences, testimonials, projects };